---
sidebar: sidebar 
permalink: scpivs44_mount_a_backup.html 
keywords:  
summary: 如果您想访问备份中的文件，您可以从备份中挂载传统数据存储。您可以将备份挂载到创建备份的同一 ESXi 主机，或者挂载到具有相同类型的 VM 和主机配置的备用 ESXi 主机。您可以在主机上多次挂载数据存储。 
---
= 挂载备份
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您想访问备份中的文件，您可以从备份中挂载传统数据存储。您可以将备份挂载到创建备份的同一 ESXi 主机，或者挂载到具有相同类型的 VM 和主机配置的备用 ESXi 主机。您可以在主机上多次挂载数据存储。

您无法挂载 vVol 数据存储。

.开始之前
* 确保备用 ESXi 主机可以连接到存储
+
如果要挂载到备用 ESXi 主机，则必须确保备用 ESXi 主机可以连接到存储并具有以下条件：

+
** 与原始主机相同的 UID 和 GID
** SnapCenter Plug-in for VMware vSphere版本的虚拟设备与原始主机的相同


* 使用 iSCSI 协议时，请确保存储系统的启动器已映射到 ESXi 主机。使用NVMe协议时，添加控制器以将所需的子系统映射到ESXi主机。
* 清理陈旧的 LUN/命名空间
+
由于 ESXi 主机每个数据存储只能发现一个唯一的 LUN/命名空间，因此如果发现多个 LUN/命名空间，操作将会失败。如果您在上一个挂载操作完成之前启动挂载操作，或者手动克隆 LUN/命名空间，或者在卸载操作期间未从存储中删除克隆，则可能会发生这种情况。为了避免发现多个克隆，您应该清理存储上所有陈旧的 LUN/命名空间。



.关于此任务
如果数据存储所在的FabricPool的存储层不可用，则挂载操作可能会失败。

.步骤
. 在 VMware vSphere 客户端快捷方式页面中选择 *存储*。
. 右键单击数据存储并选择*SnapCenter Plug-in for VMware vSphere*>*安装备份*。
. 在*Mount Datastore*页面上，选择备份和备份位置（主位置或辅助位置），然后选择*Finish*。
. 可选：要验证数据存储是否已挂载，请执行以下操作：
+
.. 在工具栏中选择“*菜单*”，然后从下拉列表中选择“*存储*”。
.. 左侧导航窗格在列表顶部显示您安装的数据存储。
+
为防止在克隆卷时创建新的快照，请关闭SnapVault卷的ONTAP计划。先前存在的快照不会被删除。




