---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflow__restore_deleted_vms.html 
keywords:  
summary: 要使用适用于SnapCenter Plug-in for VMware vSphere对虚拟机备份执行还原操作，必须遵循规定的 REST API 调用顺序。 
---
= 用于恢复已删除虚拟机的 REST API 工作流
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
要使用适用于SnapCenter Plug-in for VMware vSphere对虚拟机备份执行还原操作，必须遵循规定的 REST API 调用顺序。

对于每个 REST API，添加 `\https://<server>:<port>`在 REST API 的前面形成一个完整的端点。

|===
| 步骤 | REST API | 注释 


| 1 | 前往
`\http://<vCenter-IP>/mob` | 从 VMware 管理对象 URL 中查找 VM UUID。记下您要恢复的 VM 的 *uuid*。 


| 2 | `/4.1/vm/{uuid}/backups` | `Get VM Backups`获取指定 VM 的备份列表。传递步骤 1 中的 *uuid*。记下您要恢复的备份的 *backupId*。 


| 3 | `/4.1/vm/backups/{backupId}/
snapshotlocations` | `Get snapshot locations`获取指定备份的快照的位置。传递步骤 2 中的 *backupId*。注意*snapshotLocationsList*信息。 


| 4 | `/4.1/vm/{moref}/backups/
availableesxhosts` | `Get available ESX Hosts`获取存储备份的主机的信息。注意*availableEsxHostsList*信息。 


| 5 | `/4.1/vm/{uuid}/backups/
{backupId}/restore` | `Restore VM from a backup using uuid or restore a deleted VM`恢复指定的备份。传递步骤 1 中的 *uuid*。传递步骤 2 中的 *backupId*。在 *restoreLocations* 属性中传递步骤 3 和 4 中的信息。如果虚拟机备份是部分备份，请设置 `restartVM`参数为“false”。  *注意：*您无法恢复作为模板的虚拟机。 
|===