---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: 您可以创建、修改、删除备份资源组，以及对资源组进行备份操作。 
---
= 管理资源组
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以创建、修改、删除备份资源组，以及对资源组进行备份操作。


NOTE: 资源组在虚拟存储控制台 (VSC) 中称为备份作业。



== 暂停和恢复资源组的操作

您可以暂时禁止在资源组上启动计划操作。稍后当您需要时，您可以启用这些操作。

.步骤
. 在 SCV 插件的左侧导航窗格中，选择 *资源组*，选择一个资源组并选择 *暂停*（或选择 *恢复*）。
. 在确认框中，选择*OK*进行确认。


.完成后
在“资源组”页面上，暂停资源的作业状态为 `Under_Maintenance`。您可能需要滚动到表格右侧才能看到“作业状态”列。

恢复备份操作后，作业状态将更改为 `Production`。



== 修改资源组

您可以在 vCenter 中的资源组中删除或添加资源、分离或附加策略、修改计划或修改任何其他资源组选项。

.关于此任务
如果要修改资源组的名称，请不要在虚拟机、数据存储区、策略、备份或资源组名称中使用以下特殊字符：

% & * $ # @ ！\ / ： * ？“ < > - | ; ' ，以及空格。允许使用下划线字符 (_)。

.步骤
. 在 SCV 插件的左侧导航窗格中，选择 *资源组*，然后选择一个资源组并选择 *编辑*。
. 在“编辑资源组”向导的左侧列表中，选择要修改的类别并输入您的更改。
+
您可以在多个类别中进行更改。您还可以在此选项中编辑二级受保护资源。

. 选择“*下一步*”，直到看到“摘要”页面，然后选择“*完成*”。




== 删除资源组

如果不再需要保护资源组中的资源，则可以在 vCenter 中删除该资源组。在从 vCenter 中删除SnapCenter Plug-in for VMware vSphere之前，必须确保删除所有资源组。

.关于此任务
所有资源组删除操作均以强制删除的方式执行。删除操作会从 vCenter 资源组中分离所有策略、从SnapCenter Plug-in for VMware vSphere中删除资源组，并删除资源组的所有备份和快照。


NOTE: 在SnapVault关系中，无法删除最后一个快照；因此，无法删除资源组。在删除属于SnapVault关系的资源组之前，您必须使用 System Manager 或使用ONTAP CLI 删除SnapVault关系，然后必须删除最后一个快照。

.步骤
. 在 SCV 插件的左侧导航窗格中，选择 *资源组*，然后选择一个资源组并选择 *删除*。
. 在*删除资源组*确认框中，选择*确定*进行确认。

