---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_from_vmdks.html 
keywords:  
summary: 您可以从 Windows 客户操作系统上的 VMDK 还原一个或多个文件或文件夹。 
---
= 从 VMDK 还原客户机文件和文件夹
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以从 Windows 客户操作系统上的 VMDK 还原一个或多个文件或文件夹。

.关于此任务
默认情况下，附加的虚拟磁盘可用 24 小时，然后自动分离。您可以在向导中选择在还原操作完成时自动删除会话，也可以随时手动删除来宾文件还原会话，或者可以在*来宾配置*页面中延长时间。

来宾文件或文件夹恢复性能取决于两个因素：正在恢复的文件或文件夹的大小；以及正在恢复的文件或文件夹的数量。如果要恢复的数据集大小相同，则恢复大量小文件可能比恢复少量大文件花费的时间比预期的要长。


IMPORTANT: 一台虚拟机上同时只能运行一个连接或还原操作。您不能在同一台虚拟机上运行并行连接或恢复操作。


IMPORTANT: 访客恢复功能允许您查看和恢复系统和隐藏文件以及查看加密文件。不要尝试覆盖现有的系统文件或将加密文件恢复到加密文件夹。在恢复操作期间，客户文件的隐藏、系统和加密属性不会保留在恢复的文件中。查看或浏览保留分区可能会导致错误。

.步骤
. 从 vSphere 客户端快捷方式窗口中，选择“*主机和集群*”并选择一个 VM。
. 右键单击虚拟机并选择 * SnapCenter Plug-in for VMware vSphere* > *Guest File Restore*。
. 在“*恢复范围*”页面上，通过执行以下操作指定包含要附加的虚拟磁盘的备份：
+
.. 在“*备份名称*”表中，选择包含要附加的虚拟磁盘的备份。
.. 在 *VMDK* 表中，选择包含要还原的文件或文件夹的虚拟磁盘。
.. 在“*位置*”表中，选择要附加的虚拟磁盘的位置（主位置或辅助位置）。


. 在*客人详情*页面上，执行以下操作。
+
.. 选择虚拟磁盘的连接位置：
+
|===
| 选择此选项... | 如果… 


| 使用来宾虚拟机  a| 
您需要将虚拟磁盘附加到启动向导之前右键单击的 VM，然后选择右键单击的 VM 的凭据。


NOTE: 必须已经为虚拟机创建凭据。



| 使用客户文件恢复代理虚拟机  a| 
您想要将虚拟磁盘附加到代理虚拟机，然后选择代理虚拟机。


NOTE: 在开始连接和恢复操作之前，必须配置代理虚拟机。

|===
.. 选择*发送电子邮件通知*选项。
+
如果您希望在连接操作完成且虚拟磁盘可用时收到通知，则需要此选项。通知电子邮件包括虚拟磁盘名称、虚拟机名称以及 VMDK 新分配的驱动器号。

+

TIP: 启用此选项是因为来宾文件恢复是异步操作，并且可能需要一些时间才能为您建立来宾会话。

+
此选项使用在 vCenter 中设置 VMware vSphere 客户端时配置的电子邮件设置。



. 查看摘要，然后选择*完成*。
+
在选择“*完成*”之前，您可以返回向导中的任意页面并更改信息。

. 等待附加操作完成。
+
您可以在 Dashboard 作业监视器中查看操作的进度，也可以等待电子邮件通知。

. 要查找要从附加虚拟磁盘还原的文件，请从 vSphere 客户端快捷方式窗口中选择 * SnapCenter Plug-in for VMware vSphere*。
. 在左侧导航窗格中选择“*Guest File Restore*”>“*Guest Configuration*”。
+
在来宾会话监控表中，您可以通过选择 *... 显示有关会话的其他信息。  *在右栏。

. 选择通知电子邮件中列出的虚拟磁盘的客户文件还原会话。
+
所有分区都分配有一个驱动器号，包括系统保留分区。如果 VMDK 有多个分区，您可以通过在客户机文件浏览页面顶部的驱动器字段中的下拉列表中选择驱动器来选择特定的驱动器。

. 选择*浏览文件*图标来查看虚拟磁盘上的文件和文件夹列表。
+
当您双击文件夹来浏览并选择单个文件时，获取文件列表时可能会有时间延迟，因为获取操作是在运行时执行的。

+
为了更方便地浏览，您可以在搜索字符串中使用过滤器。过滤器区分大小写，Perl 表达式中没有空格。默认搜索字符串是 `.`*.下表显示了一些 Perl 搜索表达式的示例。

+
|===
| 这个表情…… | 搜索… 


| 。 | 除换行符之外的任何字符。 


| .* | 任何字符串。这是默认设置。 


| a | 字符 a。 


| ab | 字符串 ab。 


| a [竖线] b | 字符 a 或 b。 


| 一个* | 字符 a 的零个或多个实例。 


| a+ | 字符 a 的一个或多个实例。 


| 一个？ | 字符 a 的零个或一个实例。 


| 斧头} | 字符 a 恰好有 x 个实例。 


| 斧头，} | 字符 a 至少有 x 个实例。 


| a{x,y} | 字符 a 的实例至少有 x 个，最多有 y 个。 


| \ | 转义特殊字符。 
|===
+
访客文件浏览页面除了显示所有其他文件和文件夹外，还显示所有隐藏文件和文件夹。

. 选择一个或多个要还原的文件或文件夹，然后选择“选择还原位置”。
+
要恢复的文件和文件夹列在“选定文件”表中。

. 在“选择恢复位置”页面中，指定以下内容：
+
|===
| 选项 | 描述 


| 恢复路径 | 输入将恢复所选文件的来宾的 UNC 共享路径。  IPv4 地址示例： `\\10.60.136.65\c$` IPv6地址示例： `\\fd20-8b1e-b255-832e--61.ipv6-literal.net\C\restore` 


| 如果原始文件存在  a| 
如果要还原的文件或文件夹已存在于还原目标中，请选择要采取的操作：始终覆盖或始终跳过。


NOTE: 如果该文件夹已经存在，则该文件夹的内容将与现有文件夹合并。



| 恢复成功后断开访客会话 | 如果您希望在恢复操作完成时删除来宾文件恢复会话，请选择此选项。 
|===
. 选择*恢复*。
+
您可以在仪表板作业监视器中查看还原操作的进度，也可以等待电子邮件通知。发送电子邮件通知所需的时间取决于恢复操作完成所需的时间长度。

+
通知电子邮件包含一个附件，其中包含恢复操作的输出。如果恢复操作失败，请打开附件以获取更多信息。


