---
sidebar: sidebar 
permalink: scpivs44_view_status_information.html 
keywords:  
summary: 您可以在 vSphere 客户端仪表板上查看状态信息。状态信息每小时更新一次。 
---
= 查看状态信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在 vSphere 客户端仪表板上查看状态信息。状态信息每小时更新一次。

.步骤
. 从 vCenter 客户端快捷方式页面中，选择SnapCenter Plug-in for VMware vSphere。
. 在 SCV 的左侧导航窗格中，选择 *仪表板* > *状态*。
. 查看概览状态信息或选择链接以获取更多详细信息，如下表所列。
+
|===
| 此仪表板磁贴... | 显示以下信息... 


 a| 
最近的工作活动
 a| 
最近三到五次备份、恢复和装载作业。

** 选择工作 ID 即可查看有关该工作的更多详细信息。
** 选择“查看全部”转到“作业监视器”选项卡，查看所有作业的更多详细信息。




 a| 
作业
 a| 
在选定的时间窗口内执行的每种作业类型（备份、还原和装载）的计数。将光标悬停在图表的某个部分上可以查看该类别的更多详细信息。



 a| 
最新保护摘要
 a| 
选定时间窗口内主虚拟机和辅助虚拟机或数据存储区的数据保护状态摘要。

** 选择下拉菜单以选择*VMs*或*Datastores*。
** 对于二级存储，选择 * SnapVault* 或 * SnapMirror*。
** 将光标悬停在图表的某个部分上，即可查看该类别中的虚拟机或数据存储的数量。在“成功”类别中，列出了每个资源的最新备份。
** 您可以通过编辑配置文件来更改时间窗口。默认值为 7 天。有关详细信息，请参阅link:scpivs44_customize_your_configuration.html["自定义您的配置"] 。
** 每次主备份或辅助备份后都会更新内部计数器。仪表板磁贴每六个小时刷新一次。刷新时间无法更改。注意：如果您使用镜像保管库保护策略，则保护摘要的计数器将显示在SnapVault摘要图表中，而不是SnapMirror图表中。




 a| 
配置
 a| 
SnapCenter Plug-in for VMware vSphere管理的每种类型对象的总数。



 a| 
存储
 a| 
生成的快照、 SnapVault和SnapMirror快照的总数以及用于主快照和二级快照的存储量。该折线图分别绘制了连续 90 天期间每天的主存储和二级存储消耗情况。存储信息每 24 小时凌晨 1:08 更新一次存储节省是逻辑容量（快照节省加上消耗的存储）与主存储的物理容量的比率。条形图显示了存储节省情况。

将光标悬停在图表上的某条线上即可查看每日的详细结果。

|===

