---
sidebar: sidebar 
permalink: scpivs44_remove_plugin.html 
keywords:  
summary: 如果不再需要使用SnapCenter数据保护功能，则必须禁用适用SnapCenter Plug-in for VMware vSphere以将其从 vCenter 中取消注册，然后从 vCenter 中删除SnapCenter Plug-in for VMware vSphere，然后手动删除剩余文件。 
---
= 删除SnapCenter Plug-in for VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果不再需要使用SnapCenter数据保护功能，则必须禁用适用SnapCenter Plug-in for VMware vSphere以将其从 vCenter 中取消注册，然后从 vCenter 中删除SnapCenter Plug-in for VMware vSphere，然后手动删除剩余文件。

.开始之前
* 您必须具有管理员权限。
* 确保没有SnapCenter作业正在运行。


.步骤
. 使用以下格式登录到SnapCenter Plug-in for VMware vSphere管理 GUI `\https://<OVA-IP-address>:8080` 。
+
部署插件时，将显示SnapCenter Plug-in for VMware vSphere的 IP 地址。

. 在左侧导航窗格中选择“*配置*”，然后取消选择“*插件详细信息*”部分中的“服务”选项以禁用该插件。
. 登录到 VMware vSphere。
. 在左侧导航器屏幕中，右键单击SnapCenter Plug-in for VMware vSphere实例（名称 `.tar`部署虚拟设备时使用的文件）并选择*从磁盘删除*。
. 如果您使用适用SnapCenter Plug-in for VMware vSphere来支持其他SnapCenter插件进行应用程序一致性备份，请登录SnapCenter并删除 vSphere 主机。


.完成后
虚拟设备仍在部署，但SnapCenter Plug-in for VMware vSphere已被删除。

删除适用SnapCenter Plug-in for VMware vSphere的主机虚拟机后，该插件可能会继续列在 vCenter 中，直到本地 vCenter 缓存刷新为止。但是，由于该插件已被删除，因此无法在该主机上执行任何SnapCenter VMware vSphere 操作。如果要刷新本地 vCenter 缓存，请首先确保设备在SnapCenter Plug-in for VMware vSphere配置页面上处于禁用状态，然后重新启动 vCenter Web 客户端服务。
