---
sidebar: sidebar 
permalink: scpivs44_restore_vms_from_backups.html 
keywords:  
summary: 还原虚拟机时，您可以使用所选的备份副本覆盖现有内容，也可以复制虚拟机。 
---
= 从备份还原虚拟机
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
还原虚拟机时，您可以使用所选的备份副本覆盖现有内容，也可以复制虚拟机。

您可以将虚拟机还原到以下位置：

* 恢复到原始位置
+
** 到原始 ESXi 主机上挂载的原始数据存储（这将覆盖原始虚拟机）


* 恢复至备用位置
+
** 到原始 ESXi 主机上挂载的其他数据存储
** 到由同一 vCenter 管理的不同 ESXi 主机上挂载的原始数据存储区
** 到由同一 vCenter 管理的不同 ESXi 主机上挂载的不同数据存储区
** 到由链接模式下的不同 vCenter 管理的不同 ESXi 主机上挂载的不同数据存储区





NOTE: 您无法将 vVol VM 还原到备用主机。


NOTE: 不支持以下恢复工作流程：添加存储虚拟机，然后执行该虚拟机的备份，然后删除存储虚拟机并添加包含相同存储虚拟机的集群，然后尝试恢复原始备份。


TIP: 为了提高 NFS 环境中恢复操作的性能，请启用 VMware 应用程序 vStorage API for Array Integration (VAAI)。

.开始之前
* 必须存在备份。
+
您必须先使用适用于SnapCenter Plug-in for VMware vSphere创建虚拟机的备份，然后才能还原虚拟机。

+

NOTE: 如果有由SnapCenter Plug-in for VMware vSphere以外的软件执行的虚拟机快照，则还原操作无法成功完成。

* 目标数据存储必须准备就绪。
+
** 还原操作的目标数据存储必须具有足够的空间来容纳所有 VM 文件的副本（例如：vmdk、vmx、vmsd）。
** 目标数据存储区不得包含因先前恢复操作失败而留下的陈旧虚拟机文件。陈旧的文件具有名称格式 `restore_xxx_xxxxxx_<filename>`。


* VM 不得处于传输状态。
+
您要恢复的虚拟机不能处于 vMotion 或 Storage vMotion 状态。

* HA 配置错误
+
将备份还原到其他位置之前，请确保 vCenter ESXi 主机摘要屏幕上没有显示 HA 配置错误。

* 恢复到不同位置
+
** 还原到其他位置时，SnapCenter Plug-in for VMware vSphere必须在作为还原操作目标的 vCenter 中运行。目标数据存储必须具有足够的空间。
** “还原到备用位置”字段中的目标 vCenter 必须是 DNS 可解析的。




.关于此任务
* VM 已取消注册并重新注册
+
虚拟机的还原操作会取消注册原始虚拟机，从备份快照还原虚拟机，然后在同一 ESXi 服务器上以相同的名称和配置注册还原的虚拟机。恢复后，您必须手动将虚拟机添加到资源组。

* 恢复数据存储
+
您无法恢复数据存储，但可以恢复数据存储中的任何虚拟机。

* 恢复 vVol 虚拟机
+
** 不支持跨虚拟机的 vVol 数据存储。由于跨 VM 的 vVol 数据存储中附加的 VMDK 未备份，因此恢复的 VM 将仅包含部分 VMDK。
** 您无法将 vVol 还原到备用主机。
** 不支持 vVol 自动重新平衡。


* 虚拟机的 VMware 一致性快照失败
+
即使虚拟机的 VMware 一致性快照失败，虚拟机仍然会备份。您可以在还原向导中查看备份副本中包含的实体并将其用于还原操作。

* 如果虚拟机所在的FabricPool的存储层不可用，则恢复操作可能会失败。


.步骤
. 在 VMware vSphere 客户端 GUI 中，选择工具栏中的 *菜单*，然后从下拉列表中选择 *虚拟机和模板*。
+

NOTE: 如果要还原已删除的虚拟机，则必须将添加到SnapCenter Plug-in for VMware vSphere的存储虚拟机凭据 `vsadmin`或具有与 `vsadmin`。

. 在左侧导航窗格中，右键单击虚拟机，然后在下拉列表中选择“* SnapCenter Plug-in for VMware vSphere*”，然后在辅助下拉列表中选择“* 还原 *”以启动向导。
. 在*恢复*向导的*选择备份*页面上，选择要恢复的备份快照。
+
您可以搜索特定的备份名称或部分备份名称，也可以通过选择过滤器图标并选择日期和时间范围来过滤备份列表，选择是否需要包含 VMware 快照的备份、是否需要已挂载的备份以及位置。选择“*确定*”返回向导。

. 在*选择范围*页面上，在*恢复范围*字段中选择*整个虚拟机*，然后选择恢复位置，然后输入应挂载备份的目标信息。
+
在 *VM 名称* 字段中，如果存在相同的 VM 名称，则新的 VM 名称格式为 `<vm_name>_<timestamp>`。

+
恢复部分备份时，恢复操作会跳过“选择范围”页面。

. 在“选择位置”页面上，选择恢复的数据存储的位置。
+
在SnapCenter Plug-in for VMware vSphere中，您可以为FlexGroup卷选择二级存储。

. 查看摘要页面，然后选择*完成*。
. 可选：通过选择屏幕底部的“最近任务”来监控操作进度。
+
刷新屏幕以显示更新的信息。



.完成后
* 更改 IP 地址
+
如果您还原到其他位置，则必须更改新创建的 VM 的 IP 地址，以避免在配置静态 IP 地址时发生 IP 地址冲突。

* 将还原的虚拟机添加到资源组
+
尽管虚拟机已恢复，但它们不会自动添加到其以前的资源组中。因此，您必须手动将恢复的虚拟机添加到适当的资源组。


