---
sidebar: sidebar 
permalink: scpivs44_restore_guest_files_and_folders_overview.html 
keywords:  
summary: '您可以从 Windows 客户操作系统上的虚拟机磁盘 (VMDK) 还原文件或文件夹。' 
---
= 工作流程、先决条件和限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以从 Windows 客户操作系统上的虚拟机磁盘 (VMDK) 还原文件或文件夹。



== 来宾还原工作流

客户操作系统还原操作包括以下步骤：

. 附
+
将虚拟磁盘附加到客户虚拟机或代理虚拟机并启动客户文件恢复会话。

. 等待
+
等待附加操作完成后，您才可以浏览和恢复。当附加

+
操作完成后，将自动创建访客文件恢复会话，并发送电子邮件通知

+
发送。

. 选择文件或文件夹
+
在客户机文件还原会话中浏览 VMDK 并选择要还原的一个或多个文件或文件夹。

. 还原
+
将选定的文件或文件夹还原到指定位置。





== 恢复访客文件和文件夹的先决条件

在从 Windows 客户操作系统上的 VMDK 还原一个或多个文件或文件夹之前，您必须了解所有要求。

* 必须安装并运行 VMware 工具。
+
SnapCenter使用来自 VMware 工具的信息与 VMware Guest OS 建立连接。

* Windows 客户操作系统必须运行 Windows Server 2008 R2 或更高版本。
+
有关受支持版本的最新信息，请参阅 https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp互操作性矩阵工具 (IMT)"^]。

* 目标 VM 的凭据必须指定内置域管理员帐户或内置本地管理员帐户。用户名必须是“管理员”。在开始恢复操作之前，必须为要附加虚拟磁盘的 VM 配置凭据。附加操作和后续恢复操作都需要凭据。工作组用户可以使用内置的本地管理员帐户。
+

IMPORTANT: 如果您必须使用非内置管理员帐户但在 VM 内具有管理权限的帐户，则必须在来宾 VM 上禁用 UAC。

* 您必须知道要从中恢复的备份快照和 VMDK。
+
SnapCenter Plug-in for VMware vSphere不支持搜索要还原的文件或文件夹。因此，在开始之前，您必须知道相对于快照和相应 VMDK 的文件或文件夹的位置。

* 要附加的虚拟磁盘必须位于SnapCenter备份中。
+
包含要还原的文件或文件夹的虚拟磁盘必须位于使用适用于SnapCenter Plug-in for VMware vSphere虚拟设备执行的 VM 备份中。

* 要使用代理虚拟机，必须配置代理虚拟机。
+
如果要将虚拟磁盘附加到代理虚拟机，则必须在附加和恢复操作开始之前配置代理虚拟机。

* 对于名称非英文字母的文件，您必须将它们恢复到目录中，而不是作为单个文件。
+
您可以通过恢复文件所在的目录来恢复具有非字母名称的文件，例如日语汉字。

* 不支持从 Linux 客户操作系统恢复
+
您无法从运行 Linux 客户操作系统的 VM 还原文件和文件夹。但是，您可以附加 VMDK，然后手动恢复文件和文件夹。有关受支持的客户操作系统的最新信息，请参阅 https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp互操作性矩阵工具 (IMT)"^]。





== 来宾文件还原限制

从客户操作系统恢复文件或文件夹之前，您应该了解该功能不支持哪些功能。

* 您无法在来宾操作系统内恢复动态磁盘类型。
* 如果恢复加密的文件或文件夹，则不会保留加密属性。您无法将文件或文件夹还原到加密文件夹。
* 访客文件浏览页面显示隐藏的文件和文件夹，您无法过滤。
* 您无法从 Linux 客户操作系统恢复。
+
您无法从运行 Linux 客户操作系统的 VM 还原文件和文件夹。但是，您可以附加 VMDK，然后手动恢复文件和文件夹。有关受支持的客户操作系统的最新信息，请参阅 https://imt.netapp.com/matrix/imt.jsp?components=134348;&solution=1517&isHWU&src=IMT["NetApp互操作性矩阵工具 (IMT)"^]。

* 您无法从 NTFS 文件系统还原到 FAT 文件系统。
+
当您尝试从 NTFS 格式还原为 FAT 格式时，不会复制 NTFS 安全描述符，因为 FAT 文件系统不支持 Windows 安全属性。

* 您无法从克隆的 VMDK 或未初始化的 VMDK 恢复客户文件。
* 您无法恢复文件的目录结构。
+
如果选择恢复嵌套目录中的文件，则不会使用相同的目录结构恢复该文件。目录树没有恢复，只有文件。如果要恢复目录树，您可以复制结构顶部的目录本身。

* 您无法将客户文件从 vVol VM 还原到备用主机。
* 您无法恢复加密的访客文件。

