---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__mount_and_unmount_datastores.html 
keywords:  
summary: 要使用适用SnapCenter Plug-in for VMware vSphere对数据存储区备份执行挂载和卸载操作，必须遵循规定的 REST API 调用顺序。 
---
= 用于挂载和卸载数据存储的 REST API 工作流
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
要使用适用SnapCenter Plug-in for VMware vSphere对数据存储区备份执行挂载和卸载操作，必须遵循规定的 REST API 调用顺序。

对于每个 REST API，添加 `\https://<server>:<port>`在 REST API 的前面形成一个完整的端点。



== 要挂载数据存储，请遵循以下工作流程：

|===
| 步骤 | REST API | 注释 


| 1 | 前往 `\http://<vCenter-IP>/mob` | 从 VMware 管理对象 URL 中查找数据存储 moref。请注意您要挂载的数据存储的 *moref*。 


| 2 | `/4.1/datastores/{moref}/
backups` | `Get the list of backups for a datastore`获取指定数据存储的备份列表。传递步骤 1 中的 *moref*。记下您想要挂载的 *backupId*。 


| 3 | `/4.1/datastores/backups/
{backupId}/snapshotlocators` | `Get the list of Snapshot Locations`获取有关指定备份位置的详细信息。传递步骤 2 中的 *backupId*。注意 *datastore* 和 *snapshotLocationsList* 列表中的位置。 


| 4 | `/4.1/datastores/{moref}/
availableEsxHosts` | `Get the list of Available Esxi Hosts`获取可用于挂载操作的 ESXi 主机列表。传递步骤 1 中的 *moref*。注意*availableEsxHostsList*信息。 


| 5 | `/4.1/datastores/backups/
{backupId}/mount` | `Mount datastores for a backup`挂载指定的数据存储备份。传递步骤 2 中的 *backupId*。在 *datastore* 和 *location* 属性中，传递来自 `snapshotLocationsList`在步骤 3 中。在 *esxHostName* 属性中，传递步骤 4 中 *availableEsxHostsList* 的信息。 
|===


== 要卸载数据存储，请遵循以下工作流程：

|===
| 步骤 | REST API | 注释 


| 1 | `/4.1/datastores/backups/
{backupId}/mounted` | `Get the list of mounted datastores` 。请注意您想要卸载的数据存储*moref*。 


| 2 | `/4.1/datastores/unmount` | `UnMount datastores for a backup`卸载指定的数据存储备份。传递步骤 1 中的数据存储 *moref*(s)。 
|===