---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__attach_and_detach_vmdks.html 
keywords:  
summary: 要使用适用于SnapCenter Plug-in for VMware vSphere对 VMDK 执行连接和分离操作，必须遵循规定的 REST API 调用顺序。 
---
= 用于连接和分离 VMDK 的 REST API 工作流
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
要使用适用于SnapCenter Plug-in for VMware vSphere对 VMDK 执行连接和分离操作，必须遵循规定的 REST API 调用顺序。

对于每个 REST API，添加 `\https://<server>:<port>`在 REST API 的前面形成一个完整的端点。



== 要连接 VMDK，请遵循以下工作流程：

|===
| 步骤 | REST API | 注释 


| 1 | 前往 `\http://<vCenter-IP>/mob` | 从 VMware 管理对象 URL 中查找 VM moref。请注意您想要附加 VMDK 的 VM 的 *moref*。 


| 2 | `/4.1/vm/{moref}/backups` | `Get VM Backups`获取指定 VM 的备份列表。传递步骤 1 中的 *moref*。记下您要恢复的备份的 *backupId*。 


| 3 | `/4.1/vm/{moref}/backups/
{backupId}/vmdklocations` | `Get VMDK Locations`获取指定 VM 的 VMDK 列表。传递步骤 2 中的 *backupId* 和步骤 1 中的 *moref*。注意*vmdkLocationsList*信息。 


| 4 | `/4.1/vm/{moref}/attachvmdks`  a| 
`Attach VMDKs`将指定的 VMDK 附加到原始 VM。传递步骤 2 中的 *backupId* 和步骤 1 中的 *moref*。将步骤 3 中的 *vmdkLocationsList* 传递给 *vmdkLocations* 属性。


NOTE: 要将 VMDK 附加到不同的 VM，请在 alternativeVmMoref 属性中传递目标 VM 的 moref。

|===


== 要分离 VMDK，请遵循以下工作流程：

|===
| 步骤 | REST API | 注释 


| 1 | 前往 `\http://<vCenter-IP>/mob` | 从 VMware 管理对象 URL 中查找 VM moref。请注意您想要分离 VMDK 的 VM 的 *moref*。 


| 2 | `/4.1/vm/{moref}/backups` | `Get VM Backups`获取指定 VM 的备份列表。传递步骤 1 中的 *moref*。记下您要恢复的备份的 *backupId*。 


| 3 | `/4.1/vm/{moref}/backups/
{backupId}/vmdklocations` | `Get VMDK Locations`获取指定 VM 的 VMDK 列表。传递步骤 2 中的 *backupId* 和步骤 1 中的 *moref*。注意*vmdkLocationsList*信息。 


| 4 | `/4.1/vm/{moref}/detachvmdks` | `Detach VMDKs`分离指定的 VMDK。传递步骤 1 中的 *moref*。将步骤 3 中的 VMDK *vmdkLocationsList* 详细信息传递给 *vmdksToDetach* 属性。 
|===