---
sidebar: sidebar 
permalink: scpivs44_disable_and_enable_plugin.html 
keywords:  
summary: 如果您不再需要SnapCenter数据保护功能，则必须更改SnapCenter Plug-in for VMware vSphere的配置。例如，如果您在测试环境中部署了插件，则可能需要在该环境中禁用SnapCenter功能，并在生产环境中启用它们。 
---
= 禁用和启用SnapCenter Plug-in for VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您不再需要SnapCenter数据保护功能，则必须更改SnapCenter Plug-in for VMware vSphere的配置。例如，如果您在测试环境中部署了插件，则可能需要在该环境中禁用SnapCenter功能，并在生产环境中启用它们。

.开始之前
* 您必须具有管理员权限。
* 确保没有SnapCenter作业正在运行。


.关于此任务
当您禁用适用SnapCenter Plug-in for VMware vSphere时，所有资源组都将被暂停，并且该插件将在 vCenter 中取消注册为扩展。

启用适用SnapCenter Plug-in for VMware vSphere时，该插件将在 vCenter 中注册为扩展，所有资源组都处于生产模式，并且所有计划都已启用。

.步骤
. 可选：备份SnapCenter Plug-in for VMware vSphere，以防您想要将其还原到新的虚拟设备。
+
link:scpivs44_back_up_the_snapcenter_plug-in_for_vmware_vsphere_mysql_database.html["备份SnapCenter Plug-in for VMware vSphere"] 。

. 使用以下格式登录到SnapCenter Plug-in for VMware vSphere管理 GUI `\https://<OVA-IP-address>:8080` 。使用部署时设置的管理员用户名和密码以及使用维护控制台生成的 MFA 令牌登录。
+
部署插件时，将显示SnapCenter Plug-in for VMware vSphere的 IP 地址。

. 在左侧导航窗格中选择“*配置*”，然后取消选择“*插件详细信息*”部分中的“服务”选项以禁用该插件。
. 确认您的选择。
+
** 如果您仅使用适用SnapCenter Plug-in for VMware vSphere来执行虚拟机一致性备份
+
该插件已禁用，无需采取进一步措施。

** 如果您使用适用SnapCenter Plug-in for VMware vSphere执行应用程序一致性备份
+
该插件已被禁用，需要进一步清理。

+
... 登录到 VMware vSphere。
... 关闭虚拟机。
... 在左侧导航器屏幕中，右键单击SnapCenter Plug-in for VMware vSphere实例（名称 `.ova`部署虚拟设备时使用的文件）并选择*从磁盘删除*。
... 登录到SnapCenter并删除 vSphere 主机。





