---
sidebar: sidebar 
permalink: scpivs44_overview_of_different_snapcenter_guis.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere是一个独立插件，与其他SnapCenter插件不同。您必须使用 vCenter 中的 VMware vSphere 客户端 GUI 执行 VM、VMDK 和数据存储区的所有备份和还原操作。 
---
= 不同SnapCenter GUI 的概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在SnapCenter环境中，您必须使用适当的 GUI 来执行数据保护和管理操作。

SnapCenter Plug-in for VMware vSphere是一个独立插件，与其他SnapCenter插件不同。您必须使用 vCenter 中的 VMware vSphere 客户端 GUI 执行 VM、VMDK 和数据存储区的所有备份和还原操作。您还可以使用 Web 客户端 GUI 仪表板来监控受保护和未受保护的虚拟机列表。对于所有其他SnapCenter插件（基于应用程序的插件）操作（如备份和恢复以及作业监控），您可以使用SnapCenter GUI。

为了保护虚拟机和数据存储区，您可以使用 VMware vSphere 客户端界面。Web 客户端 GUI 与存储系统上的NetApp快照技术集成。这使您能够在几秒钟内备份虚拟机和数据存储区，并在不使 ESXi 主机脱机的情况下恢复虚拟机。

还有一个管理 GUI，用于SnapCenter Plug-in for VMware vSphere执行管理操作。

下表显示了SnapCenter GUI 执行的操作。

|===
| 使用此 GUI... | 要执行这些操作... | 并访问这些备份... 


| SnapCenter vSphere 客户端 GUI | VM 和数据存储备份 VMDK 连接和分离 数据存储挂载和卸载 VM 和 VMDK 恢复 来宾文件和文件夹恢复 | 使用 VMware vSphere 客户端 GUI 备份虚拟机和数据存储区。 


| SnapCenter GUI | 备份和恢复虚拟机上的数据库和应用程序，包括保护 Microsoft SQL Server、Microsoft Exchange 和 Oracle 的数据库。数据库克隆 | 使用SnapCenter GUI 执行备份。 


| SnapCenter Plug-in for VMware vSphere | 修改网络配置 生成支持包 修改 NTP 服务器设置 禁用/启用插件 | 不适用 


| vCenter 图形用户界面 | 为 vCenter Active Directory 用户添加 SCV 角色为用户或组添加资源访问权限 | 不适用 
|===
对于虚拟机一致的备份和恢复操作，您必须使用 VMware vSphere 客户端 GUI。虽然可以使用 VMware 工具执行某些操作，例如挂载或重命名数据存储，但这些操作不会在SnapCenter存储库中注册，也不会被识别。

SnapCenter不支持数据库和虚拟机的单个快照。必须独立安排和运行虚拟机和数据库的备份，即使数据库和虚拟机托管在同一卷中，也会创建单独的快照。必须使用SnapCenter GUI 安排基于应用程序的备份；必须使用 VMware vSphere 客户端 GUI 安排 VM 一致的备份。
