---
sidebar: sidebar 
permalink: scpivs44_create_backup_policies_for_vms_and_datastores.html 
keywords:  
summary: 在使用适用于SnapCenter Plug-in for VMware vSphere虚拟机和数据存储区之前，必须创建备份策略。 
---
= 为虚拟机和数据存储创建备份策略
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在使用适用于SnapCenter Plug-in for VMware vSphere虚拟机和数据存储区之前，必须创建备份策略。

.开始之前
* 您必须已经阅读了先决条件。
* 您必须配置辅助存储关系。
+
** 如果您要将快照复制到镜像或保管库辅助存储，则必须配置关系，并且SnapCenter管理员必须已为源卷和目标卷分配存储虚拟机。
** 要将快照成功传输到 NFS 或 VMFS 数据存储区上 Version-FlexibleMirror 关系的辅助存储，请确保SnapMirror策略类型为异步镜像，并且选中了“all_source_snapshots”选项。
** 当二级存储（镜像保管库）上的快照数量达到最大限制时，注册备份和在备份操作中应用保留的活动将失败，并出现以下错误： `This snapshot is currently used as a reference snapshot by one or more SnapMirror relationships. Deleting the snapshot can cause future SnapMirror operations to fail.`
+
要解决此问题，请为二级存储配置SnapMirror保留策略，以避免达到快照的最大限制。

+
有关管理员如何向用户分配资源的信息，请参阅 https://docs.netapp.com/us-en/snapcenter/get-started/rbac-snapcenter.html["有关使用基于角色的访问控制的SnapCenter信息"^]。



* 如果您想要虚拟机一致的备份，则必须安装并运行 VMware 工具。需要 VMware 工具来使虚拟机静止。  vVol VM 不支持 VM 一致性备份。
* SnapMirror主动同步使业务服务即使在整个站点发生故障时也能继续运行，支持应用程序使用辅助副本透明地进行故障转移。
+

NOTE: SnapMirror主动同步仅支持 VMFS 数据存储区。

+
要保护SnapMirror主动同步部署上的 VMFS 数据存储区，作为SnapCenter管理员，您需要：

+
** 按照技术报告中的描述配置集群和中介： https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/mediator-install-task.html["为SnapMirror主动同步配置ONTAP调解器和集群"] 。
** 将与 VMFS 数据存储库关联的卷添加到一致性组，并使用 _AutomatedFailOver_ 或 _AutomatedFailOverDuplex_ 保护策略在两个ONTAP存储系统之间创建数据保护关系。从ONTAP 9.15.1 版本开始支持 _AutomatedFailOverDuplex_ 策略。





NOTE: 在扇出配置中，第三站点不支持一致性组。

.关于此任务
这些向导页面上的大多数字段都是不言自明的。以下信息描述了您可能需要指导的一些字段。

.步骤
. 在 SCV 插件的左侧导航窗格中，选择 *Policies*。
. 在“*策略*”页面上，选择“*创建*”以启动向导。
. 在*新备份策略*页面上输入策略名称和描述。
+
** 链接模式
+
在链接模式下，每个 vCenter 都有一个单独的虚拟设备。因此，您可以在各个 vCenter 中使用重复的名称。但是，您必须在与资源组相同的 vCenter 中创建该策略。

** 不支持的字符
+
请勿在虚拟机、数据存储区、群集、策略、备份或资源组名称中使用以下特殊字符：% & * $ # @ ! \ / ： * ？“ < > - | ; ' ，以及空格。

+
允许使用下划线字符 (_)。



. 指定频率设置。
+
该策略仅指定备份频率。备份的具体保护计划在资源组中定义。因此，两个或多个资源组可以共享相同的策略和备份频率，但具有不同的备份计划。

. 选中*锁定期*复选框以启用快照锁定。您可以选择主快照和次快照锁定期限为天/月/年。
+

NOTE: 无论ONTAP SnapMirror策略中设置的保留值如何，在指定的辅助快照锁定期之前都不会删除辅助快照副本。

. 指定保留设置。
+

IMPORTANT: 如果您计划启用SnapVault复制，则应将保留计数设置为 2 个备份或更高。如果将保留计数设置为 1 个备份，则保留操作可能会失败。这是因为第一个快照是SnapVault关系的参考快照，直到较新的快照复制到目标。

+

NOTE: 最大保留值为 1018 个备份。如果保留设置的值高于底层ONTAP版本支持的值，则备份将失败。对于跨数据存储来说也是如此。



. 在“*复制*”字段中，指定复制到辅助存储的类型，如下表所示：
+
|===
| 对于这个领域…… | 这样做… 


| 备份后更新 Snapmirror  a| 
选择此选项可在与主备份卷具有SnapMirror关系的另一个卷上创建备份集的镜像副本。如果卷配置了镜像-保险库关系，则如果您希望将备份复制到镜像-保险库目标，则必须仅选择 *备份后更新SnapVault * 选项。


NOTE: SnapCenter Plug-in for VMware vSphere中的FlexGroup卷中的数据存储支持此选项。


NOTE: 要保护SnapMirror主动同步部署上的 VMFS 数据存储区，您需要完成“开始之前”部分中提到的先决条件并启用*备份后更新SnapMirror *。



| 备份后更新SnapVault  a| 
选择此选项可在与主备份卷具有SnapVault关系的另一个卷上执行磁盘到磁盘的备份复制。


IMPORTANT: 如果卷配置了镜像-保险库关系，则如果您希望将备份复制到镜像-保险库目标，则必须仅选择此选项。


NOTE: SnapCenter Plug-in for VMware vSphere中的FlexGroup卷中的数据存储支持此选项。



| Snapshot 标签  a| 
输入可选的自定义标签，以添加到使用此策略创建的SnapVault和SnapMirror快照。快照标签有助于区分使用此策略创建的快照与辅助存储系统上的其他快照。


NOTE: 快照标签最多允许 31 个字符。

|===
. 可选：在*高级*字段中，选择所需的字段。下表列出了高级字段的详细信息。
+
|===
| 对于这个领域…… | 这样做… 


| 虚拟机一致性  a| 
选中此框可在每次运行备份作业时使虚拟机静止并创建 VMware 快照。

vVols不支持此选项。对于 vVol VM，仅执行崩溃一致性备份。


IMPORTANT: 您必须在 VM 上运行 VMware 工具才能执行 VM 一致性备份。如果 VMware 工具未运行，则执行崩溃一致性备份。


NOTE: 当您选中 VM 一致性框时，备份操作可能需要更长时间并需要更多存储空间。在这种情况下，虚拟机首先处于静止状态，然后 VMware 执行虚拟机一致快照，然后SnapCenter执行其备份操作，然后恢复虚拟机操作。  VM 客户机内存不包含在 VM 一致性快照中。



| 包括具有独立磁盘的数据存储库 | 选中此框可将任何具有独立磁盘且包含临时数据的数据存储包含在备份中。 


| 脚本  a| 
输入您希望SnapCenter Plug-in for VMware vSphere在备份操作之前或之后运行的前置脚本或后置脚本的完全限定路径。例如，您可以运行脚本来更新 SNMP 陷阱、自动发出警报和发送日志。脚本路径在执行脚本时进行验证。


NOTE: 前言和后记必须位于虚拟设备 VM 上。要输入多个脚本，请在每个脚本路径后按 *Enter* 键，将每个脚本列在单独的行上。不允许使用字符“；”。

|===
. 选择“添加”。
+
您可以通过在“策略”页面中选择策略来验证策略是否已创建并查看策略配置。


