---
sidebar: sidebar 
permalink: scpivs44_manage_storage_systems.html 
keywords:  
summary: 在使用 VMware vSphere 客户端备份或恢复虚拟机或数据存储区之前，您必须添加存储。 
---
= 管理存储系统
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在使用 VMware vSphere 客户端备份或恢复虚拟机或数据存储区之前，您必须添加存储。



== 修改存储虚拟机

您可以使用 VMware vSphere 客户端修改在SnapCenter Plug-in for VMware vSphere中注册并用于 VM 数据保护操作的集群和存储 VM 的配置。

如果您修改作为集群的一部分自动添加的存储虚拟机（有时称为隐式存储虚拟机），则该存储虚拟机将更改为显式存储虚拟机，并且可以单独删除，而无需更改该集群中的其余存储虚拟机。在存储系统页面上，当身份验证方法是通过证书时，用户名显示为 N/A；仅当集群列表中的显式存储虚拟机将 ExplicitSVM 标志设置为 true 时，才会显示用户名。所有存储虚拟机始终列在相关集群下。


IMPORTANT: 如果您使用SnapCenter GUI 为基于应用程序的数据保护操作添加了存储虚拟机，则必须使用相同的 GUI 来修改这些存储虚拟机。

.步骤
. 在 SCV 插件的左侧导航窗格中，选择 *存储系统*。
. 在*存储系统*页面上，选择要修改的存储虚拟机，然后选择*编辑*。
. 在*编辑存储系统*窗口中，输入新值，然后选择*更新*以应用更改。




== 删除存储虚拟机

您可以使用 VMware vSphere 客户端从 vCenter 中的清单中删除存储虚拟机。


NOTE: 如果您使用SnapCenter GUI 为基于应用程序的数据保护操作添加了存储虚拟机，则必须使用相同的 GUI 来修改这些存储虚拟机。

.开始之前
您必须先卸载存储虚拟机中的所有数据存储，然后才能删除存储虚拟机。

.关于此任务
如果资源组的备份位于您删除的存储虚拟机上，则该资源组的后续备份将失败。

.步骤
. 在 SCV 插件的左侧导航窗格中，选择 *存储系统*。
. 在*存储系统*页面上，选择要删除的存储虚拟机，然后选择*删除*。
. 在*删除存储系统*确认框中，选中*删除存储系统*复选框，然后选择*是*进行确认。  *注意：*仅支持 ESXi 主机 7.0U1 及更高版本。
+
link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["重新启动 VMware vSphere 客户端服务"] 。


