---
sidebar: sidebar 
permalink: scpivs44_ontap_rbac_features_in_snapcenter.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphere可与 vCenter Server RBAC、 SnapCenter RBAC（需要支持基于应用程序的操作时）和ONTAP RBAC 配合使用，以确定特定用户可以在特定存储系统上的对象上执行哪些SnapCenter任务。 
---
= SnapCenter Plug-in for VMware vSphere）中的ONTAP RBAC 功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/



NOTE: ONTAP RBAC 仅适用于SnapCenter Server 应用程序一致性（通过 VMDK 的应用程序）作业。

[role="lead"]
ONTAP基于角色的访问控制 (RBAC) 使您能够控制对特定存储系统的访问以及用户可以在这些存储系统上执行的操作。SnapCenter Plug-in for VMware vSphere可与 vCenter Server RBAC、 SnapCenter RBAC（需要支持基于应用程序的操作时）和ONTAP RBAC 配合使用，以确定特定用户可以在特定存储系统上的对象上执行哪些SnapCenter任务。

SnapCenter使用您设置的凭据（用户名和密码）来验证每个存储系统并确定可以在该存储系统上执行哪些操作。SnapCenter Plug-in for VMware vSphere对每个存储系统使用一组凭据。这些凭据决定了可以在该存储系统上执行的所有任务；换句话说，这些凭据适用于SnapCenter，而不是单个SnapCenter用户。

ONTAP RBAC 仅适用于访问存储系统和执行与存储相关的SnapCenter任务，例如备份虚拟机。如果您没有特定存储系统的适当ONTAP RBAC 权限，则无法对该存储系统上托管的 vSphere 对象执行任何任务。

每个存储系统都有一组与其关联的ONTAP权限。

同时使用ONTAP RBAC 和 vCenter Server RBAC 可带来以下好处：

* 安全性
+
管理员可以控制哪些用户可以在细粒度的 vCenter Server 对象级别和存储系统级别执行哪些任务。

* 审计信息
+
在许多情况下， SnapCenter在存储系统上提供审计跟踪，让您可以将事件追溯到执行存储修改的 vCenter 用户。

* 可用性
+
您可以在一个地方维护控制器凭据。


