---
sidebar: sidebar 
permalink: scpivs44_how_restore_operations_are_performed.html 
keywords:  
summary: '对于 VMFS 环境，SnapCenter Plug-in for VMware vSphere使用 Storage VMotion 的克隆和挂载操作来执行还原操作。对于 NFS 环境，该插件使用本机ONTAP单文件SnapRestore (SFSR) 为大多数恢复操作提供更高的效率。对于 vVol VM，该插件使用ONTAP单文件快照还原和SnapMirror还原进行还原操作。' 
---
= 如何执行还原操作
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
对于 VMFS 环境，SnapCenter Plug-in for VMware vSphere使用 Storage VMotion 的克隆和挂载操作来执行还原操作。对于 NFS 环境，该插件使用本机ONTAP单文件SnapRestore (SFSR) 为大多数恢复操作提供更高的效率。对于 vVol VM，该插件使用ONTAP单文件快照还原 (ONTAP SFSR) 和SnapMirror还原进行还原操作。下表列出了如何执行还原操作。

|===
| 恢复操作 | 自 | 使用 


| VM 和 VMDK | 主备份 | NFS 环境： ONTAP单文件SnapRestore VMFS 环境：使用 Storage VMotion 克隆和挂载 


| VM 和 VMDK | 辅助备份 | NFS 环境： ONTAP单文件SnapRestore VMFS 环境：使用 Storage VMotion 克隆和挂载 


| 已删除的虚拟机和 VMDK | 主备份 | NFS 环境： ONTAP单文件SnapRestore VMFS 环境：使用 Storage VMotion 克隆和挂载 


| 已删除的虚拟机和 VMDK | 辅助备份 | NFS 环境：使用 Storage VMotion 进行克隆和挂载 VMFS 环境：使用 Storage VMotion 进行克隆和挂载 


| VM 和 VMDK | VM 一致的主备份 | NFS 环境： ONTAP单文件SnapRestore VMFS 环境：使用 Storage VMotion 克隆和挂载 


| VM 和 VMDK | VM 一致的辅助备份 | NFS 环境： ONTAP SnapMirror恢复 VMFS 环境：使用 Storage VMotion 克隆和挂载 


| vVol 虚拟机 | 崩溃一致的主备份 | 适用于所有协议的ONTAP单文件SnapRestore 


| vVol 虚拟机 | 崩溃一致的辅助备份 | 适用于所有协议的ONTAP SnapMirror恢复 


| FlexGroup虚拟机 | 主备份  a| 
NFS 环境：* 如果您使用的是ONTAP 9.10.1 及更高版本，则使用ONTAP单文件SnapRestore * 在ONTAP先前版本上使用 Storage VMotion 进行克隆和挂载

VMFS 环境：不支持 FlexGroups



| FlexGroup虚拟机 | 辅助备份  a| 
NFS 环境：

* 如果您使用的是ONTAP 9.10.1 及更高版本，则需要使用ONTAP SnapMirror还原
* 使用 Storage VMotion 克隆并挂载ONTAP先前版本


VMFS 环境：不支持 FlexGroups

|===

NOTE: vVol 容器重新平衡后，您无法恢复 vVol VM。

客户文件恢复操作是在 NFS 和 VMFS 环境中使用克隆和挂载操作（而非 Storage VMotion）执行的。


IMPORTANT: 在恢复操作期间，您可能会遇到错误 `Host unresolved volumes is null`或者 `Exception while calling pre-restore on SCV….Error mounting cloned LUN as datastore…`当SnapCenter Plug-in for VMware vSphere尝试重新签名克隆时，就会发生这种情况。由于 VMware 的限制，SnapCenter Plug-in for VMware vSphere无法控制高级 ESXi 主机配置中的自动重新签名值。对于 NVMe over TCP 和 NVMe over FC 存储，在添加新子系统时，SCV 无法动态添加控制器。您应该在挂载操作之前进行必要的映射。

参考 https://kb.netapp.com/mgmt/SnapCenter/SCV_clone_or_restores_fail_with_error_'Host_Unresolved_volumes_is_null'#["知识库文章：SCV 克隆或还原失败，并出现错误“主机未解析的卷为空”"^]有关该错误的更多信息。
